###
POST http://localhost:8081/api/auth/register
Content-Type: application/json

{
    "phone":"+998996672106",
    "email":"jurayevmansurbek667@gmail.Content-MD5: ",
    "password":"21admin06",
    "firstname":"Mansur",
    "lastname":"Jo'rayev"
}

###

POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
    "email":"jurayevmansurbek667@gmail.Content-MD5: ",
    "password":"21admin06"
}

