###
GET http://localhost:8081/api/users




###
POST  http://localhost:8081/api/users
Content-Type: application/json

{
    "firstname":"John ",
    "email":"examplead@gmaail.com",
    "phone":"+998889898",
    "password":"asasdasd"
}


### 
PUT  http://localhost:8081/api/users/13
Content-Type: application/json

{
    "firstname":"asdasd",
    "lastname":"asdasd",
    "email":"example34@gmail.com",
    "phone":"+998996672106",
    "password":"asdasd"
}

####
DELETE http://localhost:8081/api/users/10
Content-Type: application/json
