GET http://localhost:8081/api/video
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1cmF5ZXZtYW5zdXJiZWs2NjdAZ21haWwuQ29udGVudC1NRDU6ICIsImZpcnN0bmFtZSI6Ik1hbnN1ciIsImxhc3RuYW1lIjoiSm8ncmF5ZXYiLCJwaG9uZSI6Iis5OTg5OTY2NzIxMDYiLCJpZCI6MSwiaWF0IjoxNjU2NDI3MjU3fQ.NNGJWtCvpmmdSUaddyGicMli4-mhx5OT0fI37l2x0Ys
